"""create models

Revision ID: 58f88e54c768
Revises: 
Create Date: 2019-04-25 21:06:52.560466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f88e54c768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ingrediente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Receita',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('adicionada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Receita_Ingrediente',
    sa.Column('id_receita', sa.Integer(), nullable=False),
    sa.Column('id_ingrediente', sa.Integer(), nullable=False),
    sa.Column('porcentagem', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_ingrediente'], ['Ingrediente.id'], ),
    sa.ForeignKeyConstraint(['id_receita'], ['Receita.id'], ),
    sa.PrimaryKeyConstraint('id_receita', 'id_ingrediente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Receita_Ingrediente')
    op.drop_table('Receita')
    op.drop_table('Ingrediente')
    # ### end Alembic commands ###
