"""new model

Revision ID: c7acfa6d8c91
Revises: 58f88e54c768
Create Date: 2019-04-27 13:57:13.366962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7acfa6d8c91'
down_revision = '58f88e54c768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ReceitaIngrediente',
    sa.Column('id_receita', sa.Integer(), nullable=False),
    sa.Column('id_ingrediente', sa.Integer(), nullable=False),
    sa.Column('porcentagem', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_ingrediente'], ['Ingrediente.id'], ),
    sa.ForeignKeyConstraint(['id_receita'], ['Receita.id'], ),
    sa.PrimaryKeyConstraint('id_receita', 'id_ingrediente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReceitaIngrediente')
    # ### end Alembic commands ###
