"""empty message

Revision ID: fe67f29c1f59
Revises: c7acfa6d8c91
Create Date: 2019-04-27 14:17:42.869028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe67f29c1f59'
down_revision = 'c7acfa6d8c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Receita_Ingrediente',
    sa.Column('id_receita', sa.Integer(), nullable=False),
    sa.Column('id_ingrediente', sa.Integer(), nullable=False),
    sa.Column('porcentagem', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_ingrediente'], ['Ingrediente.id'], ),
    sa.ForeignKeyConstraint(['id_receita'], ['Receita.id'], ),
    sa.PrimaryKeyConstraint('id_receita', 'id_ingrediente')
    )
    op.drop_table('ReceitaIngrediente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ReceitaIngrediente',
    sa.Column('id_receita', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_ingrediente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('porcentagem', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['id_ingrediente'], ['Ingrediente.id'], name='ReceitaIngrediente_ibfk_1'),
    sa.ForeignKeyConstraint(['id_receita'], ['Receita.id'], name='ReceitaIngrediente_ibfk_2'),
    sa.PrimaryKeyConstraint('id_receita', 'id_ingrediente'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Receita_Ingrediente')
    # ### end Alembic commands ###
